wzc_main:
    resource: "@WzcMainBundle/Controller/"
    type:     annotation
    prefix:   /

wzc_admin:
    resource: "@WzcAdminBundle/Controller/"
    type:     annotation
    prefix:   /


_security_login:
    pattern:  /admin/login
    defaults: { _controller: WzcAdminBundle:Auth:login }

#_security_check:
#    pattern:  /login_check

login_check:
    path: /login_check

admin_login_check:
   path: /admin/login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /admin/
    defaults: { _controller: WzcAdminBundle:Index:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"