security:
    encoders:
        Wzc\MainBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    role_hierarchy:
            ROLE_ADMIN:  [ROLE_OPERATOR]

    providers:
        admin:
            entity: { class: WzcMainBundle:User, property: username }
        user:
            entity: { class: WzcMainBundle:User, property: username }
    firewalls:
        admin:
            pattern: ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            provider: admin
            logout: true
            security: true
            anonymous: true
        user:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
                provider: user
            logout: true
            security: true
            anonymous: true

    access_control:
#        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /profile, role: ROLE_USER }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
