<?php

namespace Wzc\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseEntityRepository extends EntityRepository
{
//    public function findAll(){
//
//    }

}
